site_name: Портфолио Яны
site_author: Яна Литвиновская
site_url: https://yanavlitv.github.io/
copyright: "2026 - Портфолио студента"

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple  # Основной цвет
      accent: purple        # Цвет акцентов
      toggle:
        icon: material/weather-sunny
        name: Переключить на темную тему
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Переключить на светлую тему
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
      - Лабораторная 1: labs/lab1.md
      - Лабораторная 2: labs/lab2.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight

extra_css:
  - stylesheets/images.css
