name: Deploy MkDocs Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: source/mkdocs.yml
          # REQUIREMENTS: requirements.txt  # закомментировано, т.к. файла нет